name: Dev Docker Images

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  # schedule:
  #   - cron:  '0 3 * * 1'
  workflow_dispatch:

jobs:
  docker-build:
    name: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        # ubuntu-latest leverages larger GH runner pool & completes in ~30s instead of ~3m
        runner:
          - ubuntu-22.04
          - ubicloud-standard-2
          - ubicloud-standard-4
          - ubicloud-standard-8
          - ubicloud-standard-16
          - ubicloud-standard-30
          - ubicloud-standard-2-ubuntu-2404
          - ubicloud-standard-4-ubuntu-2404
          - ubicloud-standard-8-ubuntu-2404
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Show cpu info
        run: lscpu

      - name: generate or hydrate protos
        uses: ./.github/actions/genprotos

      - name: Set Short Commit Hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build (optionally publish) PeerDB Images
        uses: docker/bake-action@v5
        with:
          files: ./docker-bake.hcl
          push: false
        env:
          SHA_SHORT: dev-${{ steps.vars.outputs.sha_short }}
          TAG: latest-dev
